services:
  azurenamingtool:
    build:
      context: https://github.com/mspnp/AzureNamingTool.git#main:src
      dockerfile: Dockerfile
    image: tfisicaro/aznamingtool
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
    ports:
      - "8081:80"
    volumes:
      - ${AZVOL_PATH}:/app/settings
      - ${AZVOL_KEYS_PATH}:/root/.aspnet/DataProtection-Keys 
    restart: unless-stopped
